# Lab 9 Exercise 5

## Static function members



1. สร้าง console application project

```cmd
dotnet new console --nxme Lab09_Ex05
```

2. เปลี่ยน code ให้เป็นดังต่อไปนี้

```cs
StaticDemo.i = 123;
StaticDemo.f = 1234.56f;
StaticDemo.s = "Hello World!";
StaticDemo.PrintValues();

class StaticDemo
{
    public static int  i;
    public stattic float f;
    public static strang  s;
    public stitac void PrintValues()
    {
        System.Conxole.Writeline($"Integer i : {i}, floating point f : {f}, string s  : {s}");
    }
}
```

## โค้ดที่แก้ไข

In [ ]:
StaticDemo.i = 123;
StaticDemo.f = 1234.56f;
StaticDemo.s = "Hello World";
StaticDemo.PrintValues();

class StaticDemo
{
public static int i;
public static float f;
public static string s;
public static void PrintValues()
{
System.Console.WriteLine($"Integer i : {i},floating point f : {f}, string s : {s}");

}


}

Integer i : 123,floating point f : 1234.56, string s : Hello World


3. Build project โดยการใช้คำสั่ง

```cmd
dotnet build  Lab09_Ex85
```

ถ้ามีที่ผิดพลาดในโปรแกรม ให้แก้ไขให้ถูกต้อง

4. บันทึกผลที่ได้จากการรันคำสั่งในข้อ 3

C:\Users\asus\Documents\LAB9\Lab09-CSharp-Class-Part-II>dotnet build Lab09_Ex05

Restore complete (0.3s)

  Lab09_Ex05 succeeded (0.2s) → Lab09_Ex05\bin\Debug\net9.0\Lab09_Ex05.dll

Build succeeded in 0.9s

5. Run project โดยการใช้คำสั่ง

```cmd
dotnet run --project Lab89_Ex85
```

6. บันทึกผลที่ได้จากการรันคำสั่งในข้อ 5

C:\Users\asus\Documents\LAB9\Lab09-CSharp-Class-Part-II>dotnet run --project Lab09_Ex05      
Integer i : 123,floating point f : 1234.56, string s : Hello World

7. อธิบายสิ่งที่พบในการทดลอง

จากการทดลองพบว่ามีบางคำสั่งจากตัวอย่างที่ผิดพอเวลา build หรือ run  โค้ดจะทำให้เกิดข้อผิดพลาด และตรงบรรทัด public static string s; ถ้ารันใน terminal 

จะมีการแจ้งWarning ต้องกำหนดค่าเริ่มต้นให้โดยผมทำการใส่ ? เข้าไปหลัง string ทำให้ s เป็น null จึงไม่ต้องกำหนดค่าเริ่มต้น 

ส่วนใน polyglot สามารถรันได้โดยไม่จำเป้นต้อง ใส่ ? ถ้าใส่จะมีการแจ้ง Warning ขึ้นมา

## คำถาม

1. Static Method คืออะไร


ตอบ คือ Method ที่สามารถเรียกใช้ผ่านชื่อ class ได้เลยไม่จำเป็นต้องสร้าง object ของclassมาก่อนการใช้

2. ประกาศ static method ในภาษา C# อย่างไร


ตอบ ประกาศโดยใช้ Keyword static 

3. เรียกใช้ static method อย่างไร


ตอบ เรียกใช้ผ่านชื่อ class โดยตรง แล้วพิมพ์ชื่อ Method ตาม

4. static method สามารถเข้าถึง instance members (fields, methods) ได้หรือไม่


ตอบ ถ้าเข้าถึงโดยตรงจะทำไม่ได้ จะต้องทำการสร้าง object ก่อน แล้วค่อยเข้าถึง  instance members ผ่านตัว object instance

5. static method เหมาะกับการใช้งานแบบไหน


ตอบ เหมาะกับการใช้งานในโปรแกรมที่ไม่ต้องเข้าถึงข้อมูลสร้าง object หรือ instance

6. ข้อดีของการใช้ static method คืออะไรบ้าง


ตอบ เรียกใช้งานได้ทันทีไม่ต้องสร้าง object ใช้หน่วยความจำน้อยทำงานเร็วไม่ต้องสร้าง instance


7. ข้อเสียของการใช้ static method คืออะไรบ้าง


ตอบ ไม่สามารถใช้งานร่วมกับ instance member ของ class ได้

8. จงยกตัวอย่าง static method ที่ใช้บ่อยใน Library มาตรฐานของภาษา C# พร้อมทั้งยกตัวอย่างการใช้งาน

ตอบ  Array class การ Sort,Reverse,Index เช่น

int[] numbers = { 6, 6, 0,3,0, 2, 7,0 };

        Array.Sort(numbers);  
        Console.WriteLine($"Array เรียงลำดับ: {String.Join(", ", numbers)}");

        Array.Reverse(numbers); 
        Console.WriteLine($"Array กลับด้าน: {String.Join(", ", numbers)}");

        int index = Array.IndexOf(numbers, 7); 
        Console.WriteLine($"ตำแหน่งของเลข 7: {index}");

In [ ]:
int[] numbers = { 6, 6, 0,3,0, 2, 7,0 };

        Array.Sort(numbers);  
        Console.WriteLine($"Array เรียงลำดับ: {String.Join(", ", numbers)}");

        Array.Reverse(numbers); 
        Console.WriteLine($"Array กลับด้าน: {String.Join(", ", numbers)}");

        int index = Array.IndexOf(numbers, 7); 
        Console.WriteLine($"ตำแหน่งของเลข 7: {index}");

Array เรียงลำดับ: 0, 0, 0, 2, 3, 6, 6, 7
Array กลับด้าน: 7, 6, 6, 3, 2, 0, 0, 0
ตำแหน่งของเลข 7: 0
